# TO run this set SPRING_PROFILES_ACTIVE to cloud in Run Configuration
---
spring.profiles: cloud

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver


---
spring.profiles: local, default

# this should go in the LOCAL profile
# Should access at: http://localhost:8080/h2/
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin1
    driverClassName: org.h2.Driver
